### ISSUE TITLE
crack pack minecraft dosent load

### ISSUE THREAD

**Issue by imransufi12** [sciguyryan/TheCrackPack#1011]
if you need my log its http://paste.atlauncher.com/view/d3a0b008

**Comment by evknucklehead** [comment]
You need to increase your maximum memory allocation to 4096 and your PermSize to 256. Open the Launcher's settings panel, then select the Java/Minecraft tab. Select 4096 from the Maximum Memory pop-up menu, enter 256 into the PermSize box, then click save at the bottom. Once that's done, you shouldn't run into memory problems again.

**Comment by imransufi12** [comment]
thank you it worked
