### ISSUE TITLE
Cant Play :(

### ISSUE THREAD

**Issue by 56codybanks** [sciguyryan/TheCrackPack#759]
I used to play crackpack a lot a while ago (when it came out), i left and now i'm back. Any way I updated and tried to play but i couldn't. It would load basically all of it I think and then it would say something about Permgen:

 ([19/1/2015 16:37:06 PM] Exception in thread "Reference Handler" [16:37:02] [Reference Handler/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.OutOfMemoryError: PermGen space)

 and then not do anything. I waited for like 10 min, and nothing. Here is the log: http://paste.atlauncher.com/view/06786053

Hope someone can help

**Comment by jberkers42** [comment]
You need to increase the memory and permgen allocations from their current settings:

-Xmx2048M, -XX:PermSize=128M

In the ATLauncher go to Settings -> Java/Minecraft and increase:

Maximum Memory/Ram to something between 3072 and 4096
PermGen Size to 256

Then try again.

**Comment by 56codybanks** [comment]
It worked thanks!
