### ISSUE TITLE
Launch Help

### ISSUE THREAD

**Issue by gameboyadvance** [sciguyryan/TheCrackPack#764]
So whenever I go to play it takes forever to load and 2 lines of red text comes up saying "[Client thread/ERROR] [WR-CBE|Addons]: Skipping event FMLPreInitializationEvent and marking errored mod WR-CBE|Addons since required dependency WR-CBE|Core has errored"
and I cant play. the screen is just black and says not responding. I have no idea what is going on and any ideas on what I can do would be greatly appreciated. Ive tried re-installing and same thing happens.

**Comment by evknucklehead** [comment]
Upload a full log to either Pastebin or the ATLauncher's built-in log uploader and post the link here.

**Comment by gameboyadvance** [comment]
http://pastebin.com/4k4t8MLW

**Comment by jberkers42** [comment]
Looks like you haven't allocated enough RAM to play the game:

    -Xmx1024 -XX:PermSize=128M

Make sure you allocate at least 2Gb, preferably more.  I see your system has around 3Gb or RAM, so I would recommend shutting everything else down before playing, and allocating around 2.25Gb.  Any more, and you will end up slowing your machine down.  Also increase your permgen to 256M.

The settings can be found on the Settings tab in ATLauncher, under the Java/Minecraft tab.

**Comment by gameboyadvance** [comment]
I have 4 gb of ram installed and 3.49gb usable. i have advance system care pro and it has a counter of how much ram im using and its usually never over 50%. Also how can i increase my permgen?

**Comment by gameboyadvance** [comment]
Nvm I found out how

**Comment by gameboyadvance** [comment]
Looks like it's working so far. Thanks for your help!!! c:
