### ISSUE TITLE
Updated and Can't play Server?

### ISSUE THREAD

**Issue by AsclepianWisdom** [sciguyryan/TheCrackPack#772]
Hello. 

Recently updated the crackpack and cannot play server. is there a way to fix this? Do I need to update server? If so, how?

Went to log on to server after update and before even getting into game I'm taken to a page with ''connection lost''. No idea why. This is new to me...

**Comment by evknucklehead** [comment]
Yes, every time the pack updates, you need to update both client and server.

**Comment by AsclepianWisdom** [comment]
Perfect! :) thanks
