### ISSUE TITLE
TTKAMI osmotic enchanter ticking block entity

### ISSUE THREAD

**Issue by UberUrkel** [sciguyryan/TheCrackPack#781]
So my CrackPack 2.0.3 crashed after i tried enchanting my goggles of revealing with repair 2 using a silverwood wand with thaumium wand caps.
I found the crash report (only showing relevant part):
http://pastebin.com/prbGWVZW

-- Block entity being ticked --
Details:
	Name: ttinkerer:enchanter // thaumic.tinkerer.common.block.tile.TileEnchanter
	Block type: ID #1544 (tile.enchanter // thaumic.tinkerer.common.block.BlockEnchanter)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (402,69,-488), Chunk: (at 2,4,8 in 25,-31; contains blocks 400,0,-496 to 415,255,-481), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #1544 (tile.enchanter // thaumic.tinkerer.common.block.BlockEnchanter)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

it was a ticking block entity that caused the crash.
IMPORTANT:
-region 0.-1
-chunk 25.-31
-block 402.69.-488

Using *NBTExplorer* I found the found the problem using this route:
-r.0.-1.mca
-chunk [0,0] --> chunk [31, 31] **NO NEGATIVE NUMBERS!!**
meaning i had to convert *25.-31* using the region... region contains chunk *0,-31 to 31,-1*
so my chunk would be:
-chunk [25,1]
-level:12entries
-TileEntities:14entries (10entries)
-inside i found the "id:ttinkerer:enchanter" (working:1)
-it had 2 items: 
*item 4497 (goggles of revealing?) with damage 68
item 4474 (wand) with all aspects:10000 (100max) cap: thaumium and rod:silverwood
(currentaspects:1entry > aspects 0entries)
(totalaspects:1entry > Aspects:6Entries >aer(amount:65), ...)*

**In words:**
my goggles of revealing (id:4497, damage:68) are alongside my silverwood-thaumium wand (id:4474, rod:silverwood, cap:thaumium, aspects:10000 each, damage:54)
in the osmotic enchanter (id:ttinkerer:enchanter, working:1)

If i delete the TileEntitities with 10 entries i assume i will lose my goggles, wand AND enchanter.
My questions:
-should i remove the Tile Entity?
-should i post this in thaumcraft Github too?
-What caused the crash?
1.goggles of revealing with damage?
2.currentaspects failed to increase to their max (totalaspects aer:65, ...)
3.enchant that isn't possible on the goggles (i doubt it)

**Comment by evknucklehead** [comment]
You might be able to remove just the goggles and get back in again. They're certainly the easiest part to remake. 

As to why it happened, there was a note in the changelog for the newer versions of Thaumcraft that Thaumic Tinkerer was using some non-API code that had been removed at some point. This could be what caused your crash, but it's just speculation on my part, as the changelog didn't specify what the code was or what it was being used for. If that is the case, manually updating Thaumcraft and Thaumic Tinkerer may prevent it from happening again. No guarantees, though.

**Comment by UberUrkel** [comment]
Thank you for the reply.
I went and deleted the goggles, and got back in my world.
Then i tried with a diamond chestplate and it still crashed.
Indicating that the problem is the Osmotic enchanter.

I will try and update the pack (no idea how, replacing the thaumcraft file in the mod-folder with a newer version might break something)
So i'm not using the enchanter, but will get back when it's fixed.

**Comment by evknucklehead** [comment]
Did you try with a different wand? Just being thorough, here.

**Comment by UberUrkel** [comment]
just tried it with:
boots of the traveller
Silverwood/thaumic cap Sceptre.

still crashed.
