### ISSUE TITLE
Launcher stopped loading :/

### ISSUE THREAD

**Issue by DasMollo** [sciguyryan/TheCrackPack#787]
Hey, I've seen this issue posted below but without the error log so it was unresolved... anyways, My launcher always seems to get to a certain point while loading and then stops during the Initializing process.  http://paste.atlauncher.com/view/cd8a7922 any way I can fix this? :)

**Comment by evknucklehead** [comment]
The crackpack cannot be effectively run on a 32-bit OS. 32-bit Java has a memory limit that is too low to load everything the pack needs. 

The only option is to install a 64-bit version of your OS and 64-bit Java. Unfortunately, this requires a complete reinstall of everything on your system, as the differences between 32-bit and 64-bit are too big to allow an upgrade install.

**Comment by DasMollo** [comment]
Ok thanks! Ill see what I can do about it :)
