### ISSUE TITLE
I can't hit mobs

### ISSUE THREAD

**Issue by Splazing** [sciguyryan/TheCrackPack#797]
For some reason I can't hit mobs nor swing/punch "the air". I can only swing/punch when I'm hitting blocks. It doesn't matter what I'm holding. I can still trow/shoot. I need help.

**Comment by evknucklehead** [comment]
Are you playing single player or on a server?

It sounds somewhat like a configuration problem, or a restriction put in place by a server-side script of some sort.

If you're playing single player, try reinstalling the pack.

**Comment by Splazing** [comment]
I ended up deleting the pack and re-installing it. It worked. Thanks for your time anyway ^_^
