### ISSUE TITLE
world crash

### ISSUE THREAD

**Issue by were58** [sciguyryan/TheCrackPack#822]
http://paste.atlauncher.com/view/4bc4af3e

**Comment by evknucklehead** [comment]
Looks like one of your crafting pillars is broken. You'll need to use NBT Explorer to find and delete that pillar in order to continue. Use the coordinates in the error report with the chunk finder in NBT Explorer to find the region and chunk you need to look in.

**Comment by iKurama** [comment]
@evknucklehead https://dinnerbone.com/minecraft/tools/coordinates/ Just like that.

**Comment by evknucklehead** [comment]
He needs to use NBT Explorer to fix the error anyway, why not use the built-in tool to go directly where he needs to be?

**Comment by were58** [comment]
Had a issue with Nbt Explorer so i used McEdit and manuelly deleted the block but thank you
