### ISSUE TITLE
My world will load but then it crashes

### ISSUE THREAD

**Issue by XxmeatloverxX** [sciguyryan/TheCrackPack#835]
for some reason my after my world loads and i am walking around the it freezes and then crashes.
and here is the crash log link http://pastebin.com/puqeVzGy

**Comment by evknucklehead** [comment]
Often times render crashes are caused by bad video drivers. Check to make sure you are running the latest version for your card from the chip maker's website (AMD/ATI, Nvidia, and Intel are the three most common.)

**Comment by XxmeatloverxX** [comment]
i am able to load my world with the drivers i have and play around for 2 minutes or so then it freezes and the crashes

**Comment by evknucklehead** [comment]
That doesn't matter. Driver-related crashes don't always happen immediately. Sometimes it can take a while for an affected object to appear in the world.

**Comment by XxmeatloverxX** [comment]
ive been looking at amd nvidia and intel and it says i have custom drivers so i dont no and my computer is a hp pavilion

**Comment by XxmeatloverxX** [comment]
i tried loading my world up and it freezed right away and crashed and here the crash log http://pastebin.com/TW8Fu2Gs

**Comment by evknucklehead** [comment]
Okay, here is where you can find the latest driver for your chip: http://downloadcenter.intel.com/download/24596/Intel-Iris-and-HD-Graphics-Driver-for-Windows-7-8-8-1-64-bit
Also, take optifine out. It tends to cause more problems than it solves.

**Comment by XxmeatloverxX** [comment]
i downloaded the latest driver does it automaticly update my update

**Comment by XxmeatloverxX** [comment]
*drivers

**Comment by evknucklehead** [comment]
No, it won't automatically update the drivers. However, you can check that site periodically to see if there is an update available.

Make sure you open the file you downloaded to install the new driver. You only need to do this once per driver version. When that's done, try running the CrackPack again to see if the error still occurs.
