### ISSUE TITLE
Ars Magica Inscription Table UI Too Big

### ISSUE THREAD

**Issue by xanderhunter** [sciguyryan/TheCrackPack#856]
I am trying to make my first spell and when I go to use the Inscription Table I cant see the top of the UI to put the spell components into the bottom part.

**Comment by evknucklehead** [comment]
Set your UI scaling to Small or Normal instead of Large or Auto.

**Comment by xanderhunter** [comment]
Irksome, I have to set it to small and that's pretty terrible.
