### ISSUE TITLE
Server Not Booting Up

### ISSUE THREAD

**Issue by Ahren07** [sciguyryan/TheCrackPack#864]
So im having some issues with my server not booting up, It gets to UU Graph built and then just says Auto Saved world for several hours, anyone have an idea why this is?

Here is the pastebin link to what the console says before it just stops the boot: http://pastebin.com/EAZi8HFi

**Comment by evknucklehead** [comment]
Gah, I hate Multicraft. It takes valuable lines out of error reports like this.

Also, it's a bit odd that the console is adding new lines at the top instead of the bottom.

Which version of the pack are you running? IC2 has not been part of the standard install since pack version 1.1.1.0.
