### ISSUE TITLE
Launch Server Fail after downloaded

### ISSUE THREAD

**Issue by BlueVizor** [sciguyryan/TheCrackPack#865]
When I tried to launch my CrackPack server, the launch could not launch because it cannot read the .jar  1.7.10 file. What should I do?

It shows this when I try to launch it...

OS is 64
Error: Unable to access jarfile %SERVERJAR%
Press any key to continue. . .

**Comment by evknucklehead** [comment]
Have you made any changes to the LaunchServer.bat file since the server was created? Also, what folder is ATLauncher running from?

**Comment by BlueVizor** [comment]
The LaunchServer.bat file is NOT in the servers file and is actually in the Configs file and under theLibraries file. So when I found it, it was actually in the wrong file. Should I move the file to the servers file?

**Comment by evknucklehead** [comment]
Yes, LaunchServer.bat should be in the server install's main directory. If it got moved somehow, move it back and try again.

The puzzling thing for me is how the file ended up there in the first place. Following the recommended process has always put the server files in the right places for me.

**Comment by BlueVizor** [comment]
It doesn't seem to make a difference. It also shows that the files may have been placed in the wrong location. Should I uninstall everything and start over? If so do you have an updated video that can show me?
