### ISSUE TITLE
Ars Magica 2 Crash

### ISSUE THREAD

**Issue by EpicChuck** [sciguyryan/TheCrackPack#887]
An attempt to summon the Winter Boss has crashed my game. Not entirely sure this happens, but now whenever I try to load up the world. I have about 2 seconds before the game crashes again. Help? Here's the log... http://paste.atlauncher.com/view/41eb52cd

**Comment by evknucklehead** [comment]
First thing to try is to set particles to minimum before you open the world, as it is a particle that is throwing the error. If that doesn't work, you'll need to go into either NBT Explorer or MCEdit and delete the particle in question. (Not entirely sure if MCEdit can delete particles, but if it can it would be easier to work with.)

**Comment by EpicChuck** [comment]
Changing particles to minimal didn't work, but will quickly destroying the inlays or the topaz/ice cancel the spawning and stop the particles?

**Comment by EpicChuck** [comment]
Destroying the inlays worked. Now would the problem happen again if I attempted the spawning? Or should I try a different boss?

**Comment by evknucklehead** [comment]
I would try a different boss to be on the safe side. There might just be a problem with the Winter Boss in the version the pack uses.

**Comment by EpicChuck** [comment]
I looked into it more and I watched the Mianite crew spawn several just fine, so I moved biomes and tried again (after backing up my world) and everything went fine. Thanks for the help!
