### ISSUE TITLE
Loading Problem

### ISSUE THREAD

**Issue by Silverhawkes** [sciguyryan/TheCrackPack#908]
I have a brand new gaming computer with 16Gb of Ram, 4.7 CPU and a nice video card but for some reason when I try and load up Crackpack it takes forever to load, and once I get it it times me out. Here is the log report http://pastebin.com/j2zbXXk5 any help would be greatly appreciated. I've tried installing everything. It's really strange, my old computer seemed to load the game faster and didn't see as 'jerky' when in game. I'm using is a 2TB (2TBx1) SATA-III 6.0Gb/s 64MB Cache 7200RPM HDD, and the video card is a AMD Radeon R9 290 4GB GDDR5 PCIe 3.0 x16 Video Card. I'm not running anything else in the background but Firefox web browser. Would the driver for the video card effect the loading though? Cause it takes about 8 minutes to even load, shouldn't be that long should it? I don't remember what the java was on the old machine, but it was no where near as up to date as this one. Checked what version of Java I'm using, it says Version 4 build 1.8.0_40-b26. 

Also, does windows 8.1 have anything to do with this cause my old machine was Windows 7?

**Comment by evknucklehead** [comment]
Unfortunately, the log file that ATLauncher saves into its folder only includes what the launcher itself does. The rest of the log is handled by FML and can be found in the instance's logs folder as fml-client-latest.log.

As for the loading the pack, yes, it does take a long time. The biggest contributing factors are the speed of the processor, RAM speed (not amount), how many of the optional mods you've installed (not a huge impact, but still a factor), Hard Drive speed, Hard Drive Fragmentation, internet connection speed (for all the mods that do version checks), and time-outs from mods trying to check for versions but not getting a timely response from their servers. 

To give a good baseline, my machine which has a Core 2 Quad running at 2.66 GHz, DDR2 800 RAM, 7200 RPM SATA II HD, and Geforce 8600 GT typically loads the pack in about 5 minutes. Running the pack off of my 2-disk RAID 0 set (a pair of 1TB 7200 RPM SATA II drives) makes very little difference in load time.

The biggest factor, of course, is the sheer number of mods that need to load. That's about 188 mod components with the recommended install. My best advice is to just be patient and enjoy the game once it does load.

**Comment by Silverhawkes** [comment]
I'm using a new computer I got this year, brief specs on it. 

OS: Win. 8.1
CPU: AMD FX-9590 4.70 GHz (5.0GHz Turbo) Eight-Core AM3+ CPU 8MB 
HDD:2TB (2TBx1) SATA-III 6.0Gb/s 64MB Cache 7200RPM HDD (Single Drive)
MEMORY:16GB (8GBx2) DDR3/2133MHz Dual Channel Memory (ADATA XPG V3)

I do understand because of the intensive mod loading it will load slow, I can deal with it. I can't enjoy the game cause once it does fully load, I'm only getting between 1-4 fps can't play it at that. Odd thing is, nothing has changed, My server is with Nodecraft, my internet hasn't changed, my old PC a win 7 with 8GB Ram runs the game fine, good FPS and everything.

**Comment by evknucklehead** [comment]
Okay, I guess I misunderstood the problem. The first thing to do is check that the optional mod FastCraft is installed. It helps fix a few issues with MC 1.7.10's rendering speed, at the cost of some rare graphical glitches.

Next, make sure your video drivers are up-to-date from AMD's website.

Another thing to try is to keep your render distance somewhere between 8 and 16 chunks. With each level of render distance, the game will require more and more memory to load everything it can see. 

For example, at 2 chunks, the game only shows 9 chunks, the one you're in, and the 8 neighboring chunks. At 3, it shows those plus the 12 chunks that surround them. By the time you get to 8 chunks, you're looking at up to 225 chunks. At 16, it's 961, and at 32, you're looking at up to 3969 chunks. All of this is not factoring in chunks that you've moved away from that haven't been unloaded yet. 

Playing on a server alleviates some of this, as the server handles the actual changes to what's going on in those chunks, plus the server having its own render distance setting which will lower yours if it's higher. The client does try to guesstimate these changes, but it doesn't need to focus on it like the server does.

Keep in mind that these are general speed suggestions, as there may be something specific going on with your machine that we can't see without the proper logs. To help us help you, launch the game from the launcher, try to get into whatever server you were trying to get to, then, if it still lags out, open the launcher's console window and click the Upload Log button. Then paste the link into a new message here.

**Comment by Silverhawkes** [comment]
Ev, thank you so much for your help. I installed the FasCraft mod and it totally changed everything. It's working perfect now. Thank you so much, really do appreciate the time and effort you put into helping me with this. Thank you!!
