### ISSUE TITLE
Server doesnt work

### ISSUE THREAD

**Issue by joshonatirfire** [sciguyryan/TheCrackPack#924]
When ever i start up my server using the universal .jar i get a bunch of code and nothing starts up 
but if i start it from the other .jar it loads but the mods dont work

**Comment by joshonatirfire** [comment]
and the .bat doesnt work

**Comment by evknucklehead** [comment]
A couple of important questions: First, what does the .bat file say when you try to run it? Second, what OS are you running, and what version of Java? Finally, how much RAM does your computer have total?

**Comment by joshonatirfire** [comment]
my .bat says this
OS is 64
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=256M; support wa
s removed in 8.0
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Press any key to continue . . .

**Comment by joshonatirfire** [comment]
my java is version 8 update 31 though i am getting version 8 update 40

**Comment by joshonatirfire** [comment]
my RAM is 8.00 GB with 7.46 usable

**Comment by evknucklehead** [comment]
That's what the file says when you run it. I was asking what it said inside the file itself, which you can see by right-clicking the file and selecting Edit to open it in Notepad. 

That said, I think I can see the problem. It's acting like you're running the 32-bit version of Java. You need to download the 64-bit version of Java from http://www.java.com/en/download/manual.jsp and install it.

**Comment by joshonatirfire** [comment]
ok well the .bat says this and im getting 64 bit 
@ECHO OFF

:: When setting the memory below make sure to include the amount of ram letter. M = MB, G = GB. Don't use 1GB for example, it's 1G ::

:: This is 64-bit memory ::
set memsixtyfour=2G

:: This is 32-bit memory - maximum 1.2G ish::
set memthirtytwo=1G

:: Don't edit past this point ::

if $SYSTEM_os_arch==x86 (
  echo OS is 32
  set mem=%memthirtytwo%
) else (
  echo OS is 64
  set mem=%memsixtyfour%
)
java -Xmx%mem% -XX:MaxPermSize=256M -jar forge-1.7.10-10.13.2.1277-universal.jar nogui
PAUSE

**Comment by joshonatirfire** [comment]
nvm thanks it works now
