### ISSUE TITLE
Cant launch The Crack Pack

### ISSUE THREAD

**Issue by Alex678** [sciguyryan/TheCrackPack#937]
I recently tried too play the crack pack for the first time and the download went fine but when I try too launch it, it wont work. It looks like every thing goes fine until the very end of the launch. Did not work once. here is the Log: http://paste.atlauncher.com/view/dd77b523

**Comment by evknucklehead** [comment]
>[10/4/2015 15:40:45 PM] You're using 32 bit Java on a 64 bit Windows install!

You need to install the 64-bit version of Java. It can be found at http://www.java.com/en/download/manual.jsp listed as Windows Offline (64-bit).

Once that's installed, make sure your maximum memory setting in the launcher is set to 3-4 GB or more, but not more than half your total memory if possible.

**Comment by Alex678** [comment]
Thank you for helping me, it works now.
