### ISSUE TITLE
Angel Rings and Morph Flight Broken?

### ISSUE THREAD

**Issue by 6unn4r** [sciguyryan/TheCrackPack#943]
Neither the Angel Rings from Extra Utilities nor the flying mobs in Morph are working on the server or in single player. I checked the config files, and everything pertinent is set to true for each individual mod. Is there something else that could be turning these settings off?

**Comment by evknucklehead** [comment]
Make sure flying is enabled in the server.properties file for the server.

Morph also requires visiting certain dimensions (at least The Nether, possibly The End as well) before using the flight capabilities.

Not sure what's wrong with your Angel Rings, though.

**Comment by 6unn4r** [comment]
After enabling flying, the ring works fine when cheated in with NEI. However, when I attempt to create any unstable ingots, the recipe does not work. The config is set up correctly, with everything enabled, so I have no idea what's going on.

**Comment by evknucklehead** [comment]
Did you activate the Division Sigil before attempting to make the ingots?

**Comment by 6unn4r** [comment]
I did indeed. Lagged the hell out of everything. I actually figured out that the crafting table I had was from natura and not vanilla. Everything is working just fine now. Thanks for the help.

**Comment by evknucklehead** [comment]
Extra Utilities is so picky about what crafting table you use. Drove me nuts when I had tried doing that with a Natura table the first time.

One tip I have if you want to have the unstable ingots for more than ten seconds is to craft semi-stable nuggets then craft those into ingots. Big downside is it costs 9x more diamonds to do it this way, but it's completely safe to use the ingots whenever you want.

**Comment by 6unn4r** [comment]
We have stacks and stacks of diamonds, so I just might try that... Tartarite hammers mine everything ever. Thanks for the help, man.
