### ISSUE TITLE
HELP! I don't know whats wrong. Also whenever i open ATL it says i'm not using the right Java when i have Java version 8!

### ISSUE THREAD

**Issue by sharksfan28** [sciguyryan/TheCrackPack#951]
http://paste.atlauncher.com/view/5fa6ee48
This is my log the error does not really say much but i'm very new to this stuff and really just want to play if you guys can help me fix this it'd be greatly appreciated!

**Comment by sharksfan28** [comment]
Update: I uninstalled the old version of Java and now minecraft starts but freezes on the mojang screen. Hers is the log: http://paste.atlauncher.com/view/8a25e060 is there anything I need to do or am I just being impatient?

**Comment by evknucklehead** [comment]
This is odd. The first log says you're running 64-bit Java 6 under Windows 7, but the second says 32-bit Java 8 under Windows XP. The only way to run the pack is with a 64-bit OS and 64-bit Java 7 or 8. I'm not even sure the 64-bit versions of Java 7 and 8 will even run on the x64 version of XP, which the second log doesn't even show. 

Check that you installed the 64-bit version of Java 8 and uninstalled Java 6 from your computer. Also check that the Java binaries on your system are not set to run in XP compatibility mode. To do this, open the window for your hard drive and do a search for java.exe, javaw.exe, and javaws.exe. Open the properties for each file and make sure none of them have anything checked under the Compatibility tab. You'll need admin rights to uncheck any boxes that have been checked.

**Comment by sharksfan28** [comment]
All is good now the game is running and im able to play thank you very much!
