### ISSUE TITLE
Won't launch anymore

### ISSUE THREAD

**Issue by shiroishinigami** [sciguyryan/TheCrackPack#954]
At first my world wasn't loading so i deleted the usercache.json file but now it won't load past the mojang logo it stops and won't finish initializing.

log: http://paste.atlauncher.com/view/99ba071d

**Comment by evknucklehead** [comment]
Looks like it was almost there. I would suggest bumping your maximum memory up to 3.5 or 4 GB, as well as updating your java install. I have slightly less available RAM than your system and I can usually run at 4GB fairly well, as long as I don't go on huge exploration trips.

**Comment by shiroishinigami** [comment]
thank you for the advise it started working
