### ISSUE TITLE
need help mod rejections

### ISSUE THREAD

**Issue by mateeex** [sciguyryan/TheCrackPack#964]
when i try to join a server
![454545454545454](https://cloud.githubusercontent.com/assets/12202819/7436166/f4f84308-f04a-11e4-950c-b9cc7e54f1c4.PNG) but i cant find what i need to do to get rid of the mods

**Comment by evknucklehead** [comment]
This means that the server owner decided not to include those two Optional mods when they started the server. You'll need to disable them to access the server.

Under the Instances panel of the launcher, click the "Edit Mods" button under your CrackPack instance. In the window that comes up, select Enchanting Plus and Soul Shards Reborn from the list on the left, then click the "Disable Mod" button. This will move those two mods from the left side to the right side. Click "Close" then try connecting to the server again.

Remember to re-enable those two before switching back to any Single-Player worlds you've been using them in.

**Comment by mateeex** [comment]
there must be 2 other mods i disable Soul shards reborn and enchanting plus there is still the same problem
i even tride to create a new instance and not installing the mods

**Comment by evknucklehead** [comment]
Confirm with the server owner what versions of what mods they have installed and make sure you use the same set. Beyond that, I'm not sure what to tell you.

**Comment by mateeex** [comment]
fixed it now thx for the tip
